paypal_url: https://www.paypal.com/cgi-bin/webscr
paypal_email: paypal@bentproductions.biz
google_maps_key: ABQIAAAAeBPm_-KwgwjbZtYJENq_NxSXaGM-1g05mGX6VFl9XFniu-YNshSTS7GIAFDjvGzJ53sScZO7htf4xw
asset_host: http://assets%d.playfulbent.com
flickr_api_key: 602d84f6664de4a28c0c17d4402ddc79
flickr_shared_secret: 8efd3392a6cb946d
