paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr
paypal_email: payments@playfulbent.com
google_maps_key: ABQIAAAAeBPm_-KwgwjbZtYJENq_NxT2gEarVg5Z7ax6cK4j8CNFWrqRgRSqDzTXjPkqz80sBYjUYwDBaombxA
flickr_api_key: 2a8764233e0d991553857f5f5d0490ab
flickr_shared_secret: 7c7e089b1f6a298d
support_address: craig@craigambrose.com